package io.cour

case class Emoji(name: String, code: String, shortCodes: List[String])

object Emoji {
  val GrinningFace: Emoji = Emoji(name = "Grinning Face", code = "😀", shortCodes = List(":grinning:"))
  val GrinningFaceWithBigEyes: Emoji = Emoji(name = "Grinning Face with Big Eyes", code = "😃", shortCodes = List(":smiley:"))
  val GrinningFaceWithSmilingEyes: Emoji = Emoji(name = "Grinning Face with Smiling Eyes", code = "😄", shortCodes = List(":smile:", ":)", ":-)"))
  val BeamingFaceWithSmilingEyes: Emoji = Emoji(name = "Beaming Face with Smiling Eyes", code = "😁", shortCodes = List(":grin:"))
  val GrinningSquintingFace: Emoji = Emoji(name = "Grinning Squinting Face", code = "😆", shortCodes = List(":laughing:", ":satisfied:"))
  val GrinningFaceWithSweat: Emoji = Emoji(name = "Grinning Face with Sweat", code = "😅", shortCodes = List(":sweat_smile:"))
  val RollingOnTheFloorLaughing: Emoji = Emoji(name = "Rolling on the Floor Laughing", code = "🤣", shortCodes = List())
  val FaceWithTearsOfJoy: Emoji = Emoji(name = "Face with Tears of Joy", code = "😂", shortCodes = List(":joy:"))
  val SlightlySmilingFace: Emoji = Emoji(name = "Slightly Smiling Face", code = "🙂", shortCodes = List())
  val UpsideDownFace: Emoji = Emoji(name = "Upside-Down Face", code = "🙃", shortCodes = List())
  val WinkingFace: Emoji = Emoji(name = "Winking Face", code = "😉", shortCodes = List(":wink:", ";)", ";-)"))
  val SmilingFaceWithSmilingEyes: Emoji = Emoji(name = "Smiling Face with Smiling Eyes", code = "😊", shortCodes = List(":blush:"))
  val SmilingFaceWithHalo: Emoji = Emoji(name = "Smiling Face with Halo", code = "😇", shortCodes = List(":innocent:"))
  val SmilingFaceWithHearts: Emoji = Emoji(name = "Smiling Face with Hearts", code = "🥰", shortCodes = List())
  val SmilingFaceWithHeartEyes: Emoji = Emoji(name = "Smiling Face with Heart-Eyes", code = "😍", shortCodes = List(":heart_eyes:"))
  val StarStruck: Emoji = Emoji(name = "Star-Struck", code = "🤩", shortCodes = List())
  val FaceBlowingAKiss: Emoji = Emoji(name = "Face Blowing a Kiss", code = "😘", shortCodes = List(":kissing_heart:"))
  val KissingFace: Emoji = Emoji(name = "Kissing Face", code = "😗", shortCodes = List(":kissing:"))
  val KissingFaceWithClosedEyes: Emoji = Emoji(name = "Kissing Face with Closed Eyes", code = "😚", shortCodes = List(":kissing_closed_eyes:"))
  val KissingFaceWithSmilingEyes: Emoji = Emoji(name = "Kissing Face with Smiling Eyes", code = "😙", shortCodes = List(":kissing_smiling_eyes:"))
  val FaceSavoringFood: Emoji = Emoji(name = "Face Savoring Food", code = "😋", shortCodes = List(":yum:"))
  val FaceWithTongue: Emoji = Emoji(name = "Face with Tongue", code = "😛", shortCodes = List(":stuck_out_tongue:", ":p", ":-p"))
  val WinkingFaceWithTongue: Emoji = Emoji(name = "Winking Face with Tongue", code = "😜", shortCodes = List(":stuck_out_tongue_winking_eye:", ";p", ";-p"))
  val ZanyFace: Emoji = Emoji(name = "Zany Face", code = "🤪", shortCodes = List())
  val SquintingFaceWithTongue: Emoji = Emoji(name = "Squinting Face with Tongue", code = "😝", shortCodes = List(":stuck_out_tongue_closed_eyes:"))
  val MoneyMouthFace: Emoji = Emoji(name = "Money-Mouth Face", code = "🤑", shortCodes = List())
  val HuggingFace: Emoji = Emoji(name = "Hugging Face", code = "🤗", shortCodes = List())
  val FaceWithHandOverMouth: Emoji = Emoji(name = "Face with Hand Over Mouth", code = "🤭", shortCodes = List())
  val ShushingFace: Emoji = Emoji(name = "Shushing Face", code = "🤫", shortCodes = List())
  val ThinkingFace: Emoji = Emoji(name = "Thinking Face", code = "🤔", shortCodes = List())
  val ZipperMouthFace: Emoji = Emoji(name = "Zipper-Mouth Face", code = "🤐", shortCodes = List())
  val FaceWithRaisedEyebrow: Emoji = Emoji(name = "Face with Raised Eyebrow", code = "🤨", shortCodes = List())
  val NeutralFace: Emoji = Emoji(name = "Neutral Face", code = "😐", shortCodes = List(":neutral_face:"))
  val ExpressionlessFace: Emoji = Emoji(name = "Expressionless Face", code = "😑", shortCodes = List(":expressionless:"))
  val FaceWithoutMouth: Emoji = Emoji(name = "Face Without Mouth", code = "😶", shortCodes = List(":no_mouth:"))
  val SmirkingFace: Emoji = Emoji(name = "Smirking Face", code = "😏", shortCodes = List(":smirk:"))
  val UnamusedFace: Emoji = Emoji(name = "Unamused Face", code = "😒", shortCodes = List(":unamused:"))
  val FaceWithRollingEyes: Emoji = Emoji(name = "Face with Rolling Eyes", code = "🙄", shortCodes = List())
  val GrimacingFace: Emoji = Emoji(name = "Grimacing Face", code = "😬", shortCodes = List(":grimacing:"))
  val LyingFace: Emoji = Emoji(name = "Lying Face", code = "🤥", shortCodes = List())
  val RelievedFace: Emoji = Emoji(name = "Relieved Face", code = "😌", shortCodes = List(":relieved:"))
  val PensiveFace: Emoji = Emoji(name = "Pensive Face", code = "😔", shortCodes = List(":pensive:"))
  val SleepyFace: Emoji = Emoji(name = "Sleepy Face", code = "😪", shortCodes = List(":sleepy:"))
  val DroolingFace: Emoji = Emoji(name = "Drooling Face", code = "🤤", shortCodes = List())
  val SleepingFace: Emoji = Emoji(name = "Sleeping Face", code = "😴", shortCodes = List(":sleeping:"))
  val FaceWithMedicalMask: Emoji = Emoji(name = "Face with Medical Mask", code = "😷", shortCodes = List(":mask:"))
  val FaceWithThermometer: Emoji = Emoji(name = "Face with Thermometer", code = "🤒", shortCodes = List())
  val FaceWithHeadBandage: Emoji = Emoji(name = "Face with Head-Bandage", code = "🤕", shortCodes = List())
  val NauseatedFace: Emoji = Emoji(name = "Nauseated Face", code = "🤢", shortCodes = List())
  val FaceVomiting: Emoji = Emoji(name = "Face Vomiting", code = "🤮", shortCodes = List())
  val SneezingFace: Emoji = Emoji(name = "Sneezing Face", code = "🤧", shortCodes = List())
  val HotFace: Emoji = Emoji(name = "Hot Face", code = "🥵", shortCodes = List())
  val ColdFace: Emoji = Emoji(name = "Cold Face", code = "🥶", shortCodes = List())
  val WoozyFace: Emoji = Emoji(name = "Woozy Face", code = "🥴", shortCodes = List())
  val DizzyFace: Emoji = Emoji(name = "Dizzy Face", code = "😵", shortCodes = List(":dizzy_face:"))
  val ExplodingHead: Emoji = Emoji(name = "Exploding Head", code = "🤯", shortCodes = List())
  val CowboyHatFace: Emoji = Emoji(name = "Cowboy Hat Face", code = "🤠", shortCodes = List())
  val PartyingFace: Emoji = Emoji(name = "Partying Face", code = "🥳", shortCodes = List())
  val SmilingFaceWithSunglasses: Emoji = Emoji(name = "Smiling Face with Sunglasses", code = "😎", shortCodes = List(":sunglasses:"))
  val NerdFace: Emoji = Emoji(name = "Nerd Face", code = "🤓", shortCodes = List())
  val FaceWithMonocle: Emoji = Emoji(name = "Face with Monocle", code = "🧐", shortCodes = List())
  val ConfusedFace: Emoji = Emoji(name = "Confused Face", code = "😕", shortCodes = List(":confused:"))
  val WorriedFace: Emoji = Emoji(name = "Worried Face", code = "😟", shortCodes = List(":worried:"))
  val SlightlyFrowningFace: Emoji = Emoji(name = "Slightly Frowning Face", code = "🙁", shortCodes = List())
  val FrowningFace: Emoji = Emoji(name = "Frowning Face", code = "☹️", shortCodes = List())
  val FaceWithOpenMouth: Emoji = Emoji(name = "Face with Open Mouth", code = "😮", shortCodes = List(":open_mouth:", ":o", ":0"))
  val HushedFace: Emoji = Emoji(name = "Hushed Face", code = "😯", shortCodes = List(":hushed:"))
  val AstonishedFace: Emoji = Emoji(name = "Astonished Face", code = "😲", shortCodes = List(":astonished:"))
  val FlushedFace: Emoji = Emoji(name = "Flushed Face", code = "😳", shortCodes = List(":flushed:"))
  val PleadingFace: Emoji = Emoji(name = "Pleading Face", code = "🥺", shortCodes = List())
  val FrowningFaceWithOpenMouth: Emoji = Emoji(name = "Frowning Face with Open Mouth", code = "😦", shortCodes = List(":frowning:", ":frowning_face:", ":(", ":-("))
  val AnguishedFace: Emoji = Emoji(name = "Anguished Face", code = "😧", shortCodes = List(":anguished:"))
  val FearfulFace: Emoji = Emoji(name = "Fearful Face", code = "😨", shortCodes = List(":fearful:"))
  val AnxiousFaceWithSweat: Emoji = Emoji(name = "Anxious Face with Sweat", code = "😰", shortCodes = List(":cold_sweat:"))
  val SadButRelievedFace: Emoji = Emoji(name = "Sad but Relieved Face", code = "😥", shortCodes = List(":disappointed_relieved:"))
  val CryingFace: Emoji = Emoji(name = "Crying Face", code = "😢", shortCodes = List(":cry:"))
  val LoudlyCryingFace: Emoji = Emoji(name = "Loudly Crying Face", code = "😭", shortCodes = List(":sob:"))
  val FaceScreamingInFear: Emoji = Emoji(name = "Face Screaming in Fear", code = "😱", shortCodes = List(":scream:"))
  val ConfoundedFace: Emoji = Emoji(name = "Confounded Face", code = "😖", shortCodes = List(":confounded:"))
  val PerseveringFace: Emoji = Emoji(name = "Persevering Face", code = "😣", shortCodes = List(":persevere:"))
  val DisappointedFace: Emoji = Emoji(name = "Disappointed Face", code = "😞", shortCodes = List(":disappointed:"))
  val DowncastFaceWithSweat: Emoji = Emoji(name = "Downcast Face with Sweat", code = "😓", shortCodes = List(":sweat:"))
  val WearyFace: Emoji = Emoji(name = "Weary Face", code = "😩", shortCodes = List(":weary:"))
  val TiredFace: Emoji = Emoji(name = "Tired Face", code = "😫", shortCodes = List(":tired_face:"))
  val YawningFace: Emoji = Emoji(name = "Yawning Face", code = "🥱", shortCodes = List())
  val FaceWithSteamFromNose: Emoji = Emoji(name = "Face with Steam From Nose", code = "😤", shortCodes = List(":triumph:"))
  val PoutingFace: Emoji = Emoji(name = "Pouting Face", code = "😡", shortCodes = List(":rage:"))
  val AngryFace: Emoji = Emoji(name = "Angry Face", code = "😠", shortCodes = List(":angry:"))
  val FaceWithSymbolsOnMouth: Emoji = Emoji(name = "Face with Symbols on Mouth", code = "🤬", shortCodes = List())
  val SmilingFaceWithHorns: Emoji = Emoji(name = "Smiling Face with Horns", code = "😈", shortCodes = List(":smiling_imp:"))
  val AngryFaceWithHorns: Emoji = Emoji(name = "Angry Face with Horns", code = "👿", shortCodes = List(":imp:"))
  val Skull: Emoji = Emoji(name = "Skull", code = "💀", shortCodes = List(":skull:"))
  val SkullAndCrossbones: Emoji = Emoji(name = "Skull and Crossbones", code = "☠️", shortCodes = List())
  val PileOfPoo: Emoji = Emoji(name = "Pile of Poo", code = "💩", shortCodes = List(":hankey:", ":poop:", ":shit:"))
  val ClownFace: Emoji = Emoji(name = "Clown Face", code = "🤡", shortCodes = List())
  val Ogre: Emoji = Emoji(name = "Ogre", code = "👹", shortCodes = List(":japanese_ogre:"))
  val Goblin: Emoji = Emoji(name = "Goblin", code = "👺", shortCodes = List(":japanese_goblin:"))
  val Ghost: Emoji = Emoji(name = "Ghost", code = "👻", shortCodes = List(":ghost:"))
  val Alien: Emoji = Emoji(name = "Alien", code = "👽", shortCodes = List(":alien:"))
  val AlienMonster: Emoji = Emoji(name = "Alien Monster", code = "👾", shortCodes = List(":space_invader:"))
  val Robot: Emoji = Emoji(name = "Robot", code = "🤖", shortCodes = List())
  val GrinningCat: Emoji = Emoji(name = "Grinning Cat", code = "😺", shortCodes = List(":smiley_cat:"))
  val GrinningCatWithSmilingEyes: Emoji = Emoji(name = "Grinning Cat with Smiling Eyes", code = "😸", shortCodes = List(":smile_cat:"))
  val CatWithTearsOfJoy: Emoji = Emoji(name = "Cat with Tears of Joy", code = "😹", shortCodes = List(":joy_cat:"))
  val SmilingCatWithHeartEyes: Emoji = Emoji(name = "Smiling Cat with Heart-Eyes", code = "😻", shortCodes = List(":heart_eyes_cat:"))
  val CatWithWrySmile: Emoji = Emoji(name = "Cat with Wry Smile", code = "😼", shortCodes = List(":smirk_cat:"))
  val KissingCat: Emoji = Emoji(name = "Kissing Cat", code = "😽", shortCodes = List(":kissing_cat:"))
  val WearyCat: Emoji = Emoji(name = "Weary Cat", code = "🙀", shortCodes = List(":scream_cat:"))
  val CryingCat: Emoji = Emoji(name = "Crying Cat", code = "😿", shortCodes = List(":crying_cat_face:"))
  val PoutingCat: Emoji = Emoji(name = "Pouting Cat", code = "😾", shortCodes = List(":pouting_cat:"))
  val SeeNoEvilMonkey: Emoji = Emoji(name = "See-No-Evil Monkey", code = "🙈", shortCodes = List(":see_no_evil:"))
  val HearNoEvilMonkey: Emoji = Emoji(name = "Hear-No-Evil Monkey", code = "🙉", shortCodes = List(":hear_no_evil:"))
  val SpeakNoEvilMonkey: Emoji = Emoji(name = "Speak-No-Evil Monkey", code = "🙊", shortCodes = List(":speak_no_evil:"))
  val KissMark: Emoji = Emoji(name = "Kiss Mark", code = "💋", shortCodes = List(":kiss:"))
  val LoveLetter: Emoji = Emoji(name = "Love Letter", code = "💌", shortCodes = List(":love_letter:"))
  val HeartWithArrow: Emoji = Emoji(name = "Heart with Arrow", code = "💘", shortCodes = List(":cupid:"))
  val HeartWithRibbon: Emoji = Emoji(name = "Heart with Ribbon", code = "💝", shortCodes = List(":gift_heart:"))
  val SparklingHeart: Emoji = Emoji(name = "Sparkling Heart", code = "💖", shortCodes = List(":sparkling_heart:"))
  val GrowingHeart: Emoji = Emoji(name = "Growing Heart", code = "💗", shortCodes = List(":heartpulse:"))
  val BeatingHeart: Emoji = Emoji(name = "Beating Heart", code = "💓", shortCodes = List(":heartbeat:"))
  val RevolvingHearts: Emoji = Emoji(name = "Revolving Hearts", code = "💞", shortCodes = List(":revolving_hearts:"))
  val TwoHearts: Emoji = Emoji(name = "Two Hearts", code = "💕", shortCodes = List(":two_hearts:"))
  val HeartDecoration: Emoji = Emoji(name = "Heart Decoration", code = "💟", shortCodes = List(":heart_decoration:"))
  val HeartExclamation: Emoji = Emoji(name = "Heart Exclamation", code = "❣️", shortCodes = List())
  val BrokenHeart: Emoji = Emoji(name = "Broken Heart", code = "💔", shortCodes = List(":broken_heart:"))
  val RedHeart: Emoji = Emoji(name = "Red Heart", code = "❤️", shortCodes = List(":heart:"))
  val OrangeHeart: Emoji = Emoji(name = "Orange Heart", code = "🧡", shortCodes = List())
  val YellowHeart: Emoji = Emoji(name = "Yellow Heart", code = "💛", shortCodes = List(":yellow_heart:"))
  val GreenHeart: Emoji = Emoji(name = "Green Heart", code = "💚", shortCodes = List(":green_heart:"))
  val BlueHeart: Emoji = Emoji(name = "Blue Heart", code = "💙", shortCodes = List(":blue_heart:"))
  val PurpleHeart: Emoji = Emoji(name = "Purple Heart", code = "💜", shortCodes = List(":purple_heart:"))
  val BrownHeart: Emoji = Emoji(name = "Brown Heart", code = "🤎", shortCodes = List())
  val BlackHeart: Emoji = Emoji(name = "Black Heart", code = "🖤", shortCodes = List())
  val WhiteHeart: Emoji = Emoji(name = "White Heart", code = "🤍", shortCodes = List())
  val HundredPoints: Emoji = Emoji(name = "Hundred Points", code = "💯", shortCodes = List(":100:"))
  val AngerSymbol: Emoji = Emoji(name = "Anger Symbol", code = "💢", shortCodes = List(":anger:"))
  val Collision: Emoji = Emoji(name = "Collision", code = "💥", shortCodes = List(":boom:", ":collision:"))
  val Dizzy: Emoji = Emoji(name = "Dizzy", code = "💫", shortCodes = List(":dizzy:"))
  val SweatDroplets: Emoji = Emoji(name = "Sweat Droplets", code = "💦", shortCodes = List(":sweat_drops:"))
  val DashingAway: Emoji = Emoji(name = "Dashing Away", code = "💨", shortCodes = List(":dash:"))
  val Hole: Emoji = Emoji(name = "Hole", code = "🕳️", shortCodes = List())
  val Bomb: Emoji = Emoji(name = "Bomb", code = "💣", shortCodes = List(":bomb:"))
  val SpeechBalloon: Emoji = Emoji(name = "Speech Balloon", code = "💬", shortCodes = List(":speech_balloon:"))
  val EyeInSpeechBubble: Emoji = Emoji(name = "Eye in Speech Bubble", code = "👁️‍🗨️", shortCodes = List())
  val LeftSpeechBubble: Emoji = Emoji(name = "Left Speech Bubble", code = "🗨️", shortCodes = List())
  val RightAngerBubble: Emoji = Emoji(name = "Right Anger Bubble", code = "🗯️", shortCodes = List())
  val ThoughtBalloon: Emoji = Emoji(name = "Thought Balloon", code = "💭", shortCodes = List(":thought_balloon:"))
  val Zzz: Emoji = Emoji(name = "Zzz", code = "💤", shortCodes = List(":zzz:"))

  val all: List[Emoji] = List(
    GrinningFace, GrinningFaceWithBigEyes, GrinningFaceWithSmilingEyes, BeamingFaceWithSmilingEyes,
    GrinningSquintingFace, GrinningFaceWithSweat, RollingOnTheFloorLaughing, FaceWithTearsOfJoy, SlightlySmilingFace,
    UpsideDownFace, WinkingFace, SmilingFaceWithSmilingEyes, SmilingFaceWithHalo, SmilingFaceWithHearts,
    SmilingFaceWithHeartEyes, StarStruck, FaceBlowingAKiss, KissingFace, KissingFaceWithClosedEyes,
    KissingFaceWithSmilingEyes, FaceSavoringFood, FaceWithTongue, WinkingFaceWithTongue, ZanyFace,
    SquintingFaceWithTongue, MoneyMouthFace, HuggingFace, FaceWithHandOverMouth, ShushingFace, ThinkingFace,
    ZipperMouthFace, FaceWithRaisedEyebrow, NeutralFace, ExpressionlessFace, FaceWithoutMouth, SmirkingFace,
    UnamusedFace, FaceWithRollingEyes, GrimacingFace, LyingFace, RelievedFace, PensiveFace, SleepyFace, DroolingFace,
    SleepingFace, FaceWithMedicalMask, FaceWithThermometer, FaceWithHeadBandage, NauseatedFace, FaceVomiting,
    SneezingFace, HotFace, ColdFace, WoozyFace, DizzyFace, ExplodingHead, CowboyHatFace, PartyingFace,
    SmilingFaceWithSunglasses, NerdFace, FaceWithMonocle, ConfusedFace, WorriedFace, SlightlyFrowningFace,
    FrowningFace, FaceWithOpenMouth, HushedFace, AstonishedFace, FlushedFace, PleadingFace, FrowningFaceWithOpenMouth,
    AnguishedFace, FearfulFace, AnxiousFaceWithSweat, SadButRelievedFace, CryingFace, LoudlyCryingFace,
    FaceScreamingInFear, ConfoundedFace, PerseveringFace, DisappointedFace, DowncastFaceWithSweat, WearyFace, TiredFace,
    YawningFace, FaceWithSteamFromNose, PoutingFace, AngryFace, FaceWithSymbolsOnMouth, SmilingFaceWithHorns,
    AngryFaceWithHorns, Skull, SkullAndCrossbones, PileOfPoo, ClownFace, Ogre, Goblin, Ghost, Alien, AlienMonster,
    Robot, GrinningCat, GrinningCatWithSmilingEyes, CatWithTearsOfJoy, SmilingCatWithHeartEyes, CatWithWrySmile,
    KissingCat, WearyCat, CryingCat, PoutingCat, SeeNoEvilMonkey, HearNoEvilMonkey, SpeakNoEvilMonkey, KissMark,
    LoveLetter, HeartWithArrow, HeartWithRibbon, SparklingHeart, GrowingHeart, BeatingHeart, RevolvingHearts, TwoHearts,
    HeartDecoration, HeartExclamation, BrokenHeart, RedHeart, OrangeHeart, YellowHeart, GreenHeart, BlueHeart,
    PurpleHeart, BrownHeart, BlackHeart, WhiteHeart, HundredPoints, AngerSymbol, Collision, Dizzy, SweatDroplets,
    DashingAway, Hole, Bomb, SpeechBalloon, EyeInSpeechBubble, LeftSpeechBubble, RightAngerBubble, ThoughtBalloon, Zzz
  )
  lazy val codeMap: Map[String, Emoji] = all.flatMap { e =>
    e.shortCodes.map(sc => (sc, e))
  }.toMap

  def unapply(text: String): Option[Emoji] = codeMap.get(text.toLowerCase)
}